### ISSUE TITLE
MAM does not properly load last tile

### ISSUE THREAD

**Issue by imphil** [optimsoc/sources#30]
See https://api.travis-ci.org/jobs/177929879/log.txt?deansi=true

The same software works when loading the memories through --meminit and not through the debug system/loadelf.

**Comment by imphil** [comment]
Actually it's independent of the application, `hello` shows the same bug: no code runs on tile 3 when initialized through the debug system.

**Comment by wallento** [comment]
Thanks, this narrows it down. I will have a look after lunch

**Comment by imphil** [comment]
Actually MAM is still writing to the memory of the last tile when we start the CPUs. The correct way to resolve this is to make sure that the memory write is finished before we do anything else. The incorrect way is to add a sleep in runelf.py.

**Comment by wallento** [comment]
Oh, yeah, I actually had the solution in my mind for a while, which is acknowledging writes. I mainly thought about it for the synchronous experience on the host side, but now we have a very good reason to fix it asap. The sleep solves it for your measurements at least..

**Comment by imphil** [comment]
Opened https://github.com/opensocdebug/hardware/issues/30 on the OSD side to get this fixed.
