### ISSUE TITLE
baremetal libraries: Fix compiler warnings

### ISSUE THREAD

**Issue by imphil** [optimsoc/sources#31]
Currently we get some compiler warnings, mostly from using wrong type qualifiers for printf(). That's not a big deal, but reducing those messages will make it easier to spot real problems. See any recent travis build log for exact details.

**Comment by ppenna** [comment]
With the above merge, compiler warnings due to printf() were solved.

Nevertheless, it is worth checking out the warnings that still remain. They may unveil some bug in the system.

Cheers,
Pedro h. Penna

**Comment by imphil** [comment]
Fixed #38
